'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
const { spawn } = require('node:child_process');
const { chromium } = require('../build/audit-tools/node_modules/playwright');
const { seedEmptyProject } = require('../tools/project-layout');

async function main() {
  const temp = await fs.mkdtemp(path.join(os.tmpdir(), 'novel-flow-debug-'));
  const project = seedEmptyProject(path.join(temp, 'project'));
  await fs.writeFile(path.join(project.scenesRoot, 'main.tds'), 'global int score = 0\nscene main {\n  say narrator "before"\n  say narrator "Score {score}"\n  goto "chapter.tds"\n}\n');
  await fs.writeFile(path.join(project.scenesRoot, 'chapter.tds'), 'scene chapter {\n  say narrator "Chapter {score}"\n}\n');
  await fs.writeFile(path.join(project.scenesRoot, 'branch.tds'), 'scene branch {\n  if score > 0 {\n    say narrator "positive"\n  } else {\n    say narrator "zero"\n  }\n}\n');
  await fs.writeFile(path.join(project.scenesRoot, 'domains.tds'), 'global int domainScore = 0\nscene domains {\n  choice "choose" {\n    "a" { set domainScore = 2 }\n    "b" { set domainScore = 5 }\n  }\n  say narrator "Domain {domainScore}"\n}\n');
  await fs.writeFile(path.join(project.scenesRoot, 'seed.tds'), 'global int seedScore = 0\nscene seed {\n  set seedScore = 7\n  say narrator "Seed {seedScore}"\n}\n');
  await fs.writeFile(path.join(project.scenesRoot, 'multi.tds'), 'scene first {\n  say narrator "First scene"\n}\nscene second {\n  say narrator "Second scene"\n}\n');
  await fs.writeFile(path.join(project.scenesRoot, 'characters.tds'), 'character hero {\n  name = "Hero Display"\n}\n');
  await fs.writeFile(path.join(project.scenesRoot, 'speaker.tds'), 'global int directValue = 8\nscene speaker {\n  say narrator str(directValue)\n  say hero "External speaker"\n}\n');
  await fs.writeFile(path.join(project.scenesRoot, 'dict.tds'), 'global dict[int] points = {"x": 0}\nscene dict_test {\n  say narrator str(points["x"])\n}\n');
  await fs.writeFile(path.join(project.scenesRoot, 'struct.tds'), 'struct Mood {\n  label: str\n  count: int\n}\nglobal Mood mood = { "label": "none", "count": 0 }\nscene struct_test {\n  say narrator "{mood.label}"\n}\n');
  const child = spawn(process.execPath, [path.resolve(__dirname, '..', 'Edit', 'server.js'), '--project', project.projectRoot], {
    cwd: path.resolve(__dirname, '..'), env: { ...process.env, PORT: '0', NOVEL_TEMP_STARTUP_WORKSPACE: '1', NOVEL_EDITOR_RECENT_FILE: path.join(temp, 'recent.json') },
    windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'],
  });
  let browser;
  try {
    let output = '';
    const base = await new Promise((resolve, reject) => {
      const timer = setTimeout(() => reject(Error(`server timeout: ${output}`)), 30000);
      const check = () => { const match = output.match(/http:\/\/127\.0\.0\.1:\d+/); if (match) { clearTimeout(timer); resolve(match[0]); } };
      child.stdout.on('data', (value) => { output += String(value); check(); });
      child.stderr.on('data', (value) => { output += String(value); check(); });
      child.once('exit', (code) => reject(Error(`server exited ${code}: ${output}`)));
    });
    browser = await chromium.launch({ channel: 'msedge', headless: true });
    const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
    page.setDefaultTimeout(15000);
    const errors = [];
    page.on('pageerror', (error) => errors.push(error.message));
    await page.goto(`${base}/index.html`);
    await page.waitForFunction(() => Boolean(document.querySelector('#scene-name')?.value));
    await page.evaluate(() => openScene('main.tds'));
    await page.locator('[data-activity="flow"]').click();
    const flow = page.frameLocator('#scene-flow-frame');
    await flow.locator('.flow-node[data-file="main.tds"]').click();
    if (process.env.NOVEL_FLOW_SCREENSHOT) await page.screenshot({ path: process.env.NOVEL_FLOW_SCREENSHOT });
    const sidebarLayout = await flow.locator('.controls').evaluate((side) => {
      const panel = side.querySelector('.flow-test-panel').getBoundingClientRect();
      const legend = side.querySelector('.legend').getBoundingClientRect();
      return { panelBottom: panel.bottom, legendTop: legend.top, panelTop: panel.top, filterBottom: side.querySelector('.flow-filters').getBoundingClientRect().bottom };
    });
    assert.ok(sidebarLayout.panelTop >= sidebarLayout.filterBottom - 1 && sidebarLayout.panelBottom <= sidebarLayout.legendTop + 1, `test controls and legend must not overlap: ${JSON.stringify(sidebarLayout)}`);
    await page.setViewportSize({ width: 900, height: 640 });
    const compactLayout = await flow.locator('.controls').evaluate((side) => ({
      panel: side.querySelector('.flow-test-panel').getBoundingClientRect().toJSON(),
      legend: side.querySelector('.legend').getBoundingClientRect().toJSON(),
      filter: side.querySelector('.flow-filters').getBoundingClientRect().toJSON(),
    }));
    assert.ok(compactLayout.panel.top >= compactLayout.filter.bottom - 1 && compactLayout.panel.bottom <= compactLayout.legend.top + 1 && compactLayout.panel.height > 100, `compact test panel overlaps: ${JSON.stringify(compactLayout)}`);
    await page.setViewportSize({ width: 1440, height: 900 });
    const mainSceneOption = flow.locator('#flow-test-scene option').first();
    assert.equal(await mainSceneOption.textContent(), 'main', 'scene selector shows only the scene name');
    assert.equal(await flow.locator('#flow-test-line').inputValue(), '2', 'scene starts at its scene declaration line by default');
    await page.waitForFunction(() => document.querySelector('#highlight .hl-start')?.textContent.includes('scene main'));
    await flow.locator('#flow-test-line').fill('4');
    const score = flow.locator('#flow-test-vars input[data-name="score"]');
    await score.waitFor();
    await page.waitForFunction(() => document.querySelector('#scene-flow-frame')?.contentDocument?.querySelector('#flow-test-run')?.disabled === false);
    await score.fill('invalid');
    await flow.locator('#flow-test-run').click();
    assert.match(await flow.locator('#flow-test-message').textContent(), /整数/);
    assert.equal(await page.locator('.debug-player-panel').count(), 0, 'invalid overrides never start playback');
    await score.fill('7');
    assert.equal(await flow.locator('#flow-test-line').inputValue(), '4', 'editing a variable must not change the selected start line');
    await flow.locator('#flow-test-run').click();
    const player = page.frameLocator('.debug-player-panel iframe');
    await player.locator('#text').getByText('Score 7').waitFor().catch(async (error) => { throw Error(`${error.message}; player=${await player.locator('#text').textContent().catch(() => '<none>')}; url=${await page.locator('.debug-player-panel iframe').getAttribute('src').catch(() => '<none>')}; line=${await flow.locator('#flow-test-line').inputValue()}; message=${await flow.locator('#flow-test-message').textContent()}; status=${await page.locator('#status').textContent()}; errors=${errors.join(' | ')}`); });
    await page.locator('[data-debug-location]').waitFor();
    assert.match(await page.locator('[data-debug-location]').textContent(), /main\.tds:4/);
    assert.equal(await page.locator('#scene-name').inputValue(), 'main.tds');
    await page.waitForFunction(() => document.querySelector('#highlight .hl-running')?.textContent.includes('Score'));
    assert.equal(await page.locator('#highlight .hl-running').count(), 1);
    const runningRow = await page.locator('#highlight .hl-running').evaluate((row) => {
      const rect = row.getBoundingClientRect();
      const editor = document.querySelector('#editor').getBoundingClientRect();
      return { background: getComputedStyle(row).backgroundColor, visible: rect.bottom > editor.top && rect.top < editor.bottom };
    });
    assert.notEqual(runningRow.background, 'rgba(0, 0, 0, 0)', 'the executing line has a visible background');
    assert.equal(runningRow.visible, true, 'the executing line is scrolled into the editor viewport');
    assert.equal(await page.locator('#editor').evaluate((element) => element.value.slice(element.selectionStart, element.selectionEnd).trim()), 'say narrator "Score {score}"');
    await player.locator('#dialogue').evaluate((element) => element.dispatchEvent(new MouseEvent('click', { bubbles: true })));
    await player.locator('#text').getByText('Chapter 7').waitFor();
    await page.waitForFunction(() => document.querySelector('#scene-name')?.value === 'chapter.tds' && document.querySelector('#highlight .hl-running')?.textContent.includes('Chapter'));
    await page.getByRole('button', { name: 'Scene Flow' }).click();
    await flow.locator('.flow-node[data-file="struct.tds"]').click();
    await flow.locator('#flow-test-vars input[data-name="mood"]').waitFor();
    await flow.locator('#flow-test-vars input[data-name="mood"]').fill('{"label":"ready","count":3}');
    await flow.locator('#flow-test-run').click();
    await player.locator('#text').getByText('ready').waitFor();
    await page.getByRole('button', { name: '停止', exact: true }).click();
    assert.equal(await page.locator('.debug-player-panel').count(), 0, 'stop closes the test player');
    await page.locator('[data-activity="flow"]').click();
    await flow.locator('.flow-node[data-file="dict.tds"]').click();
    await flow.locator('#flow-test-vars input[data-name="points"]').fill('{"x":5}');
    await flow.locator('#flow-test-run').click();
    await player.locator('#text').getByText('5', { exact: true }).waitFor();
    await page.getByRole('button', { name: 'Scene Flow' }).click();
    await flow.locator('.flow-node[data-file="branch.tds"]').click();
    await flow.locator('#flow-test-vars input[data-name="score"]').fill('9');
    await flow.locator('#flow-test-run').click();
    await player.locator('#text').getByText('positive').waitFor();
    await page.getByRole('button', { name: 'Scene Flow' }).click();
    await flow.locator('.flow-node[data-file="branch.tds"]').click();
    await flow.locator('#flow-test-line').fill('3');
    await flow.locator('#flow-test-run').click();
    await player.locator('#text').getByText('positive').waitFor();
    await page.waitForFunction(() => document.querySelector('#highlight .hl-running')?.textContent.includes('positive'));
    await page.getByRole('button', { name: 'Scene Flow' }).click();
    assert.equal(await page.locator('#highlight .hl-running').count(), 0);
    await flow.locator('.flow-node[data-file="domains.tds"]').click();
    await flow.locator('#flow-test-line').fill('7');
    await flow.locator('.flow-test-variable:has(input[data-name="domainScore"]) .flow-test-domain').getByText(/候補 2: 2 \/ 5/).waitFor();
    await flow.locator('#flow-test-vars input[data-name="domainScore"]').fill('5');
    await flow.locator('#flow-test-run').click();
    await player.locator('#text').getByText('Domain 5').waitFor();
    await page.getByRole('button', { name: 'Scene Flow' }).click();
    await flow.locator('.flow-node[data-file="seed.tds"]').click();
    await flow.locator('#flow-test-line').fill('4');
    await flow.locator('.flow-test-variable:has(input[data-name="seedScore"]) .flow-test-domain').getByText('確定: 7').waitFor();
    await flow.locator('#flow-test-run').click();
    await player.locator('#text').getByText('Seed 7').waitFor();
    await page.getByRole('button', { name: 'Scene Flow' }).click();
    await flow.locator('.flow-node[data-file="chapter.tds"]').click();
    await flow.locator('#flow-test-scene').selectOption('chapter');
    await flow.locator('#flow-test-vars input[data-name="score"]').waitFor();
    await flow.locator('#flow-test-vars input[data-name="score"]').fill('9');
    assert.equal(await flow.locator('#flow-test-vars input[data-name="score"]').inputValue(), '9');
    await flow.locator('#flow-test-run').click();
    await player.locator('#text').getByText('Chapter 9').waitFor().catch(async (error) => { throw Error(`${error.message}; text=${await player.locator('#text').textContent().catch(() => '<none>')}; input=${await flow.locator('#flow-test-vars input[data-name="score"]').inputValue().catch(() => '<none>')}; message=${await flow.locator('#flow-test-message').textContent()}; errors=${errors.join(' | ')}`); });
    await page.waitForFunction(() => document.querySelector('#scene-name')?.value === 'chapter.tds' && document.querySelector('#highlight .hl-running')?.textContent.includes('Chapter'));
    await page.getByRole('button', { name: 'Scene Flow' }).click();
    await flow.locator('.flow-node[data-file="multi.tds"]').click();
    await flow.locator('#flow-test-scene').selectOption('second');
    assert.equal(await flow.locator('#flow-test-line').inputValue(), '4', 'changing scene defaults to its scene line');
    await flow.locator('#flow-test-line').fill('2');
    assert.equal(await flow.locator('#flow-test-run').isDisabled(), true, 'a line from another scene cannot start playback');
    await flow.locator('#flow-test-line').fill('5');
    await flow.locator('#flow-test-run').click();
    await player.locator('#text').getByText('Second scene').waitFor();
    await page.getByRole('button', { name: 'Scene Flow' }).click();
    await flow.locator('#flow-test-scene').selectOption('first');
    assert.equal(await flow.locator('#flow-test-line').inputValue(), '1', 'switching scenes defaults to the new scene line');
    await flow.locator('#flow-test-run').click();
    await player.locator('#text').getByText('First scene').waitFor();
    await page.getByRole('button', { name: 'Scene Flow' }).click();
    await flow.locator('.flow-node[data-file="speaker.tds"]').click();
    const speakerNode = await page.evaluate(async () => (await (await fetch('/api/scene-graph')).json()).nodes.find((node) => node.id === 'speaker.tds'));
    assert.ok(speakerNode?.variables?.some((item) => item.name === 'hero'), 'speaker identifiers are indexed as character-variable references');
    const speakerDomains = await page.evaluate(async () => (await (await fetch('/api/flow-domains?file=speaker.tds&scene=speaker&line=2&names=hero,directValue')).json()));
    assert.deepEqual(speakerDomains.domains.hero, { kind: 'exact', values: ['{"name":"Hero Display"}'] });
    assert.deepEqual(speakerDomains.domains.directValue, { kind: 'exact', values: ['8'] });
    await flow.locator('.flow-test-variable:has(input[data-name="directValue"]) .flow-test-domain').getByText('確定: 8').waitFor();
    await flow.locator('.flow-test-variable:has(input[data-name="hero"]) .flow-test-domain').getByText(/確定:/).waitFor();
    await flow.locator('#flow-test-run').click();
    await player.locator('#text').getByText('8', { exact: true }).waitFor();
    await player.locator('#dialogue').evaluate((element) => element.dispatchEvent(new MouseEvent('click', { bubbles: true })));
    await player.locator('#text').getByText('External speaker').waitFor();
    assert.equal(await player.locator('#speaker-text').textContent(), 'Hero Display', 'direct test playback resolves an external character display name');
    await page.getByRole('button', { name: 'Scene Flow' }).click();
    await flow.locator('.flow-node[data-file="multi.tds"]').click();
    await flow.locator('#flow-test-pick-line').click();
    await page.waitForFunction(() => document.querySelector('#scene-flow-host')?.hidden === true);
    const editorPoint = await page.locator('#editor').evaluate((element) => {
      const style = getComputedStyle(element);
      const rect = element.getBoundingClientRect();
      return { x: rect.left + 60, y: rect.top + (parseFloat(style.paddingTop) || 0) + 1.5 * parseFloat(style.lineHeight) };
    });
    await page.mouse.move(editorPoint.x, editorPoint.y);
    await page.waitForFunction(() => document.querySelector('#highlight .hl-pick-hover')?.textContent.includes('First scene'));
    await page.mouse.click(editorPoint.x, editorPoint.y);
    await page.waitForFunction(() => document.querySelector('#scene-flow-host')?.hidden === false);
    await page.waitForFunction(() => document.querySelector('#scene-flow-frame')?.contentDocument?.querySelector('#flow-test-line')?.value === '2');
    assert.equal(await flow.locator('#flow-test-line').inputValue(), '2', 'clicked source line returns to Scene Flow');
    assert.match(await fs.readFile(path.join(project.scenesRoot, 'main.tds'), 'utf8'), /global int score = 0/, 'debug overrides never modify the scenario');
    assert.deepEqual(errors, []);
    console.log('PASS Scene Flow debug: line entry, variable override, player, cross-file live highlight');
  } finally {
    await browser?.close();
    if (child.exitCode === null) child.kill();
    await fs.rm(temp, { recursive: true, force: true });
  }
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
