#include <SDL3/SDL.h>
#include <SDL3_image/SDL_image.h>
#include <SDL3_ttf/SDL_ttf.h>
#include <nlohmann/json.hpp>
#include <fstream>
#include <filesystem>
#include <iostream>
using json=nlohmann::json; namespace fs=std::filesystem;
struct P{SDL_Window*w{};SDL_Renderer*r{};TTF_Font*f{};SDL_Texture*dialog{};int width=960,height=680,dx=30,dy=470,dw=900,dh=180,fx=55,tx=55,fy=495,ty=540,speakerSize=24,textSize=24;std::string title="Novel Script",font="C:/Windows/Fonts/meiryo.ttc",dialogPath,root,sp,txt;bool wait{},run=true;std::vector<json>s;size_t si{},pc{};};
static std::string val(const json&e){return e.value("kind","")=="literal"?e.value("value",""):e.value("name","");}
static void cfg(P&p,const fs::path&f){std::ifstream in(f);std::string l;while(std::getline(in,l)){auto n=l.find('=');if(n==std::string::npos||l.rfind('#',0)==0)continue;auto k=l.substr(0,n),v=l.substr(n+1);while(!k.empty()&&k.back()==' ')k.pop_back();while(!v.empty()&&v[0]==' ')v.erase(0,1);if(k=="window.title")p.title=v;else if(k=="window.width")p.width=std::stoi(v);else if(k=="window.height")p.height=std::stoi(v);else if(k=="font.path")p.font=v;else if(k=="dialog.background_image")p.dialogPath=v;else if(k=="dialog.x")p.dx=std::stoi(v);else if(k=="dialog.y")p.dy=std::stoi(v);else if(k=="dialog.width")p.dw=std::stoi(v);else if(k=="dialog.height")p.dh=std::stoi(v);else if(k=="dialog.speaker_x")p.fx=std::stoi(v);else if(k=="dialog.text_x")p.tx=std::stoi(v);else if(k=="dialog.speaker_y")p.fy=p.dy+std::stoi(v);else if(k=="dialog.text_y")p.ty=p.dy+std::stoi(v);else if(k=="dialog.speaker_size")p.speakerSize=std::stoi(v);else if(k=="dialog.text_size")p.textSize=std::stoi(v);}}
static void txt(P&p,const std::string&s,float y){if(!p.f)return;TTF_SetFontSize(p.f,y==p.fy?p.speakerSize:p.textSize);SDL_Color c{30,45,70,255};auto*q=TTF_RenderText_Blended(p.f,s.c_str(),s.size(),c);if(!q)return;auto*t=SDL_CreateTextureFromSurface(p.r,q);SDL_FRect z{(float)(y==p.fy?p.fx:p.tx),y,(float)q->w,(float)q->h};SDL_RenderTexture(p.r,t,nullptr,&z);SDL_DestroyTexture(t);SDL_DestroySurface(q);}
int main(int ac,char**av){if(ac<2){std::cerr<<"Usage: novel_player package.nsp.json\n";return 2;}json j;try{std::ifstream f(av[1]);f>>j;}catch(...){return 2;}P p;p.root=fs::path(av[1]).parent_path().string();auto g=j["program"];for(auto&s:g.value("scenes",json::array()))p.s.push_back(s);if(p.s.empty()&&!g.value("instructions",json::array()).empty())p.s.push_back(json{{"instructions",g["instructions"]}});if(p.s.empty())return 1;if(!SDL_Init(SDL_INIT_VIDEO|SDL_INIT_AUDIO)||!TTF_Init())return 1;cfg(p,fs::path(SDL_GetBasePath())/"engine_data/engine.txt");p.f=TTF_OpenFont(p.font.c_str(),24);p.w=SDL_CreateWindow(p.title.c_str(),p.width,p.height,0);p.r=SDL_CreateRenderer(p.w,nullptr);if(!p.dialogPath.empty())p.dialog=IMG_LoadTexture(p.r,(fs::path(SDL_GetBasePath())/"engine_data"/p.dialogPath).string().c_str());while(p.run){SDL_Event e;while(SDL_PollEvent(&e)){if(e.type==SDL_EVENT_QUIT)p.run=false;if(e.type==SDL_EVENT_KEY_DOWN&&p.wait)p.wait=false;}if(!p.wait&&p.pc<p.s[p.si]["instructions"].size()){auto&i=p.s[p.si]["instructions"][p.pc++];if(i["op"]=="command"&&i["name"]=="say"){p.sp=val(i["args"][0]);p.txt=val(i["args"][1]);p.wait=true;}}SDL_SetRenderDrawColor(p.r,12,15,22,255);SDL_RenderClear(p.r);SDL_FRect b{(float)p.dx,(float)p.dy,(float)p.dw,(float)p.dh};if(p.dialog)SDL_RenderTexture(p.r,p.dialog,nullptr,&b);else{SDL_SetRenderDrawColor(p.r,0,0,0,220);SDL_RenderFillRect(p.r,&b);}txt(p,p.sp,p.fy);txt(p,p.txt,p.ty);SDL_RenderPresent(p.r);SDL_Delay(16);}if(p.dialog)SDL_DestroyTexture(p.dialog);if(p.f)TTF_CloseFont(p.f);SDL_DestroyRenderer(p.r);SDL_DestroyWindow(p.w);TTF_Quit();SDL_Quit();}
