const graphBox=document.querySelector('#graph'),details=document.querySelector('#details'),status=document.querySelector('#status');let currentData=null;const style=document.createElement('style');style.textContent='.flow-folders{display:flex;align-items:flex-start;flex-wrap:wrap;gap:20px;margin-bottom:20px}.flow-folder{position:relative;flex:0 0 160px;background:#151d27;border:1px solid #2a3b4c;border-radius:6px;padding:8px}.flow-folder-edges{margin-top:16px;padding:12px;background:#0d131a;border:1px solid #243342;border-radius:6px;display:block}.flow-folder-edge{color:#8ab4f8;font:11px/1.8 ui-monospace,Consolas,monospace}';document.head.append(style);
// フォルダの転移順を左から右へ並べる
function orderFolders(folders,links){const incoming=new Map(folders.map(f=>[f,0]));links.forEach(([,to])=>incoming.set(to,(incoming.get(to)||0)+1));const result=[],left=new Set(folders);while(left.size){const ready=[...left].filter(f=>incoming.get(f)===0);if(!ready.length){result.push(...left);break}ready.forEach(f=>{result.push(f);left.delete(f);links.filter(([from])=>from===f).forEach(([,to])=>incoming.set(to,incoming.get(to)-1))})}return result}
const folderOf=f=>{const p=String(f).replaceAll('\\\\','/').split('/');return p.length>1?p.slice(0,-1).join('/'):'(root)'};
const label=f=>String(f).replaceAll('\\\\','/').split('/').pop().replace(/(?:\.novel)?\.tds$/i,'');
function link(file,text=file){const a=document.createElement('a');a.className='flow-link-button';a.href='/?scene='+encodeURIComponent(file);a.textContent=text;return a}
function group(parent,title,items){if(!items.length)return;const g=document.createElement('div');g.className='flow-detail-group';const h=document.createElement('div');h.className='group-label';h.textContent=title;g.append(h);[...new Set(items)].forEach(x=>g.append(link(x)));parent.append(g)}
function showFile(file,data){details.replaceChildren();const h=document.createElement('div');h.className='detail-title';h.textContent=file;details.append(h);group(details,'転移元',data.edges.filter(e=>e.to===file).map(e=>e.from));group(details,'転移先',data.edges.filter(e=>e.from===file).map(e=>e.to));const n=data.nodes.find(x=>x.id===file);if(n?.reachable===false){const e=document.createElement('div');e.className='flow-error';e.textContent='開始ファイルから到達できません';details.append(e)}if(n?.error){const e=document.createElement('div');e.className='flow-error';e.textContent='このファイルは解析できません';details.append(e)}if(n?.variables?.length){const g=document.createElement('div');g.className='flow-detail-group';const h2=document.createElement('div');h2.className='group-label';h2.textContent='変数';g.append(h2);n.variables.forEach(v=>{const r=document.createElement('div');r.className='flow-variable';r.textContent=`${v.name} : ${v.type||'unknown'}`;g.append(r)});details.append(g)}}
function showFolder(folder,files){details.replaceChildren();const h=document.createElement('div');h.className='detail-title';h.textContent=`${folder} / ${files.length} files`;details.append(h);const p=document.createElement('div');p.textContent='ファイルにカーソルを合わせると詳細を表示します';details.append(p);files.forEach(f=>details.append(link(f)))}
function render(data){const by=new Map;data.nodes.forEach(n=>{const f=folderOf(n.id);if(!by.has(f))by.set(f,[]);by.get(f).push(n.id)});const folders=[...by.keys()],seen=new Set,links=[];data.edges.forEach(e=>{const a=folderOf(e.from),b=folderOf(e.to),k=a+'>'+b;if(a!==b&&by.has(a)&&by.has(b)&&!seen.has(k)){seen.add(k);links.push([a,b])}});const orderedFolders=orderFolders(folders,links);const shell=document.createElement('div');shell.className='flow-shell';const row=document.createElement('div');row.className='flow-folders';orderedFolders.forEach(f=>{const b=document.createElement('div');b.className='flow-folder';const t=document.createElement('div');t.className='flow-folder-title';t.textContent=f;b.append(t);const list=document.createElement('div');list.className='flow-files';(by.get(f)||[]).forEach(file=>{const a=document.createElement('a');a.className='flow-file';const node=data.nodes.find(item=>item.id===file);if(node?.reachable===false)a.classList.add('unreachable');a.href='/?scene='+encodeURIComponent(file);a.textContent=label(file);a.title=node?.reachable===false?`${file}（開始ファイルから到達不能）`:file;a.onmouseenter=()=>showFile(file,data);list.append(a)});b.append(list);b.onmouseenter=()=>showFolder(f,by.get(f)||[]);row.append(b)});shell.append(row);const es=document.createElement('div');es.className='flow-folder-edges';const edgeTitle=document.createElement('div');edgeTitle.className='group-label';edgeTitle.textContent='接続関係 (エッジ)';es.append(edgeTitle);if(data.edges.length===0){const noEdge=document.createElement('div');noEdge.textContent='ファイル間接続はありません';noEdge.style.color='#738496';es.append(noEdge)}else{data.edges.forEach(e=>{const el=document.createElement('div');el.className='flow-folder-edge';el.textContent=`${e.from}  ──▶  ${e.to}`;es.append(el)})}shell.append(es);graphBox.replaceChildren(shell);status.textContent=`${folders.length} folders / ${data.nodes.length} files`}
document.addEventListener('click',e=>{const file=e.target.closest('.flow-file');if(!file||!currentData)return;e.preventDefault();e.stopPropagation();const folder=file.closest('.flow-folder')?.querySelector('.flow-folder-title')?.textContent;const full=[...currentData.nodes].find(n=>label(n.id)===file.textContent&&folderOf(n.id)===folder)?.id;if(full)showFile(full,currentData)},true);
const originalRender=render;render=data=>{currentData=data;originalRender(data)};fetch('/api/scene-graph').then(r=>{if(!r.ok)throw Error('Scene Flow API error: '+r.status);return r.json()}).then(render).catch(e=>{status.textContent=e.message;details.textContent=e.message});

const compactStyle=document.createElement('style');compactStyle.textContent='.flow-folder{width:95px!important;flex-basis:95px!important}';document.head.append(compactStyle);
const layoutStyle=document.createElement('style');layoutStyle.textContent='#graph{transform-origin:top left;overflow:visible}.flow-shell{transform-origin:top left;min-width:0}.flow-folders{align-items:flex-start!important;flex-wrap:wrap!important;overflow:visible!important}.flow-folder{z-index:2}.flow-files{position:absolute;left:0;top:100%;width:100%;padding-top:9px;z-index:20}.flow-folder:hover{z-index:30}.flow-folder-edges{position:relative;z-index:1}';document.head.append(layoutStyle);
const visualStyle=document.createElement('style');visualStyle.textContent='.flow-files{background:#111923;border:1px solid #385165;border-radius:6px;padding:7px;box-shadow:0 8px 18px #0008}.flow-file{padding:5px 7px;border:0;border-radius:3px;background:transparent;color:#d7e4ee}.flow-file.unreachable{color:#69727e;filter:grayscale(1);opacity:.68}.flow-file:hover{background:#294452;color:#fff}';document.head.append(visualStyle);
const clickStyle=document.createElement('style');clickStyle.textContent='.flow-file{position:relative;z-index:50;cursor:pointer;pointer-events:auto}';document.head.append(clickStyle);
document.addEventListener('pointerup',e=>{const file=e.target.closest('.flow-file');if(!file||!currentData)return;e.preventDefault();e.stopPropagation();showFile(file.title,currentData)},true);
const hoverStyle=document.createElement('style');hoverStyle.textContent='.flow-folder.open .flow-files{display:flex}';document.head.append(hoverStyle);let hoverTimer;document.addEventListener('mouseenter',e=>{const folder=e.target.closest?.('.flow-folder');if(folder){clearTimeout(hoverTimer);folder.classList.add('open')}},true);document.addEventListener('mouseleave',e=>{const folder=e.target.closest?.('.flow-folder');if(folder){hoverTimer=setTimeout(()=>folder.classList.remove('open'),250)}},true);
